name: Deploy Frontend to Firebase
on:
  push:
    branches:
      - main  # or master, depending on your default branch name

jobs:
  deploy_frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install Dependencies (Frontend)
        run: |
          cd Cuentos_Front
          npm install
          
      - name: Build Frontend
        run: |
          cd Cuentos_Front
          npm run build
          
      - name: Deploy Frontend to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          channelId: live
          projectId: generador-cuentos 